main/urls.py
from django.urls import path
from .views import login_view, home_page_view, logout_view, cancel_payments_page_view, filial_page_view, \
    cancel_payment_by_id_view, proceed_cancel_view, wallet_to_bank_acc_view
from django.contrib.auth import views

app_name = 'main'

urlpatterns = [
    path('login', views.LoginView.as_view(template_name='pages/signin.html'), name='login'),
    path('logout', logout_view, name='logout'),

    path('', home_page_view, name='home'),
    path('cancel-payments', cancel_payments_page_view, name='cancel-payments'),
    path('cancel/payments/<int:pk>', cancel_payment_by_id_view, name='cancel-payment-by-id'),
    path('cancel/payments/proceed/<int:pk>', proceed_cancel_view, name='cancel-payment-proceed'),
    path('wallet-to-bacc', wallet_to_bank_acc_view, name='wallet-to-bank'),

    path('payments/branch/<int:pk>', filial_page_view, name='payments-by-branches'),
]

merchant_unired/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/by_filial.html
{% extends 'snippets/base.html' %}
{% load humanize %}

{% block content %}
    <!-- Recent Sales Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="bg-light text-center rounded p-4">
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">Recent Sales</h6>
                <a href="">Show All</a>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-dark">
                            <th scope="col"><label>
                                <input class="form-check-input" type="checkbox">
                            </label></th>
                            <th scope="col">Date</th>
                            <th scope="col">Customer</th>
                            <th scope="col">Customer wallet</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for payment in payments %}
                          <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>{{ payment.created_at}}</td>
                            <td>{{ payment.client.first_name }}</td>
                            <td>{{ payment.client.card }}</td>
                            <td>{{ payment.amount|intcomma}}</td>
                              {% if payment.status == 1 %}
                               <td><button type="button" class="btn btn-success m-1">Success</button></td>
                                  {% else %}
                                  <td ><button type="button" class="btn btn-square btn-danger m-2"><i class="btn-close"></i></button></td>
                              {% endif %}

                          </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Recent Sales End -->
{% endblock content %}

templates/pages/cancel_payments-copy.html
{% load humanize %}
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DASHMIN - Bootstrap Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url "main:home" %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>Dashboard</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{% static "img/user.jpg" %}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{ request.user.first_name}}</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="{% url "main:home" %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Filiallar</a>
                        <div class="dropdown-menu bg-transparent border-0">

                            {% for brand_merchant in brand_merchants %}
                                <button type="button" class="btn btn-outline-primary m-2"><i class="fa fa-home me-2"></i>{{ brand_merchant.name }}</button>
                            {% endfor %}

                        </div>
                    </div>
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>To'lovni bekor qilish</a>
{#                    <a href="widget.html" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Widgets</a>#}
{#                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>#}
{#                    <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>#}
{#                    <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>#}
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="{% url 'main:home' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">{% csrf_token %}
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{% static "img/user.jpg" %}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{ request.user.first_name}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="{% url "main:logout" %}" class="dropdown-item">Log out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

             <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Recent Sales</h6>
                        <a href="">Show All</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-dark">
                                    <th scope="col"><input class="form-check-input" type="checkbox"></th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Customer</th>
                                    <th scope="col">Customer wallet</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for payment in payments %}
                                  <tr>
                                    <td><input class="form-check-input" type="checkbox"></td>
                                    <td>{{ payment.created_at}}</td>
                                    <td>{{ payment.client.first_name }}</td>
                                    <td>{{ payment.client.card }}</td>
                                    <td>{{ payment.amount|intcomma}}</td>
                                      {% if payment.status == 1 %}
                                       <td><button class="btn btn-success m-1"></button></td>
                                          {% else %}
                                          <td><button class="btn btn-square btn-danger m-2"><i class="btn-close"></i></button></td>
                                      {% endif %}
{#                                    <td><button class="btn btn-danger m-1" onclick="clicked(event)">Cancel</button></td>#}
                                    <td><button class="btn btn-danger m-1" onclick="return confirm('Are you sure?');">Cancel</button></td>

                                  </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


            <!-- Sales Chart Start -->
{#            <div class="container-fluid pt-4 px-4">#}
{#                <div class="row g-4">#}
{#                    <div class="col-sm-12 col-xl-6">#}
{#                        <div class="bg-light text-center rounded p-4">#}
{#                            <div class="d-flex align-items-center justify-content-between mb-4">#}
{#                                <h6 class="mb-0">Worldwide Sales</h6>#}
{#                                <a href="">Show All</a>#}
{#                            </div>#}
{#                            <canvas id="worldwide-sales"></canvas>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-sm-12 col-xl-6">#}
{#                        <div class="bg-light text-center rounded p-4">#}
{#                            <div class="d-flex align-items-center justify-content-between mb-4">#}
{#                                <h6 class="mb-0">Salse & Revenue</h6>#}
{#                                <a href="">Show All</a>#}
{#                            </div>#}
{#                            <canvas id="salse-revenue"></canvas>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            <!-- Sales Chart End -->


            <!-- Footer Start -->
{#            <div class="container-fluid pt-4 px-4">#}
{#                <div class="bg-light rounded-top p-4">#}
{#                    <div class="row">#}
{#                        <div class="col-12 col-sm-6 text-center text-sm-start">#}
{#                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script>
    function clicked(e)
    {
        if(!confirm('Are you sure?')) {
            e.preventDefault();
        }
    }
    </script>
</body>

</html>

templates/pages/cancel_payments.html
{% extends 'snippets/base.html' %}
{% load static %}
{% load humanize %}

{%  block content %}
    <!-- Sale & Revenue Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-chart-line fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Today Sale</p>
                        <h6 class="mb-0">UZS: {{ today_sales.amount__sum|intcomma }}</h6>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-chart-bar fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Total Sales</p>
                        <h6 class="mb-0">UZS: {{ total_sales.amount__sum|intcomma }}</h6>
                    </div>
                </div>
            </div>

            {% if is_brand %}
                <div class="col-sm-6 col-xl-3">
                    <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                        <i class="fa fa-chart-area fa-3x text-primary"></i>
                        <div class="ms-3">
                            <p class="mb-2">Bank Account Balance</p>
                            <h6 class="mb-0">UZS: {{ merchant_bank_balance|intcomma }}</h6>
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-chart-pie fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Balance(Wallet)</p>
                        <h6 class="mb-0">UZS: {{ balance|intcomma }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Sale & Revenue End -->

    <!-- Recent Sales Start -->
    <div class="container-fluid pt-4 px-4">
    <div class="bg-light text-center rounded p-4">
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h6 class="mb-0">Recent Sales</h6>
        <a href="">Show All</a>
    </div>
    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-dark">
                                    <th scope="col"><input class="form-check-input" type="checkbox"></th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Customer</th>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">Customer wallet</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for payment in payments %}
                                  <tr>
                                    <td><input class="form-check-input" type="checkbox"></td>
                                    <td>{{ payment.created_at}}</td>
                                    <td>{{ payment.client.first_name }}</td>
                                    <td>{{ payment.tr_id }}</td>
                                    <td>{{ payment.client.card }}</td>
                                    <td>{{ payment.amount|intcomma}}</td>
                                      {% if payment.status == 1 %}
                                       <td><button class="btn btn-success m-1"></button></td>
                                          {% else %}
                                          <td><button class="btn btn-danger m-1"></button></td>
                                      {% endif %}
                                  <td>
                                    {% if payment.status == 1 %}
                                        <form action='{% url 'main:cancel-payment-by-id' payment.id %}' method='GET'> {% csrf_token %}
                                            <button class="btn btn-danger m-1" type='submit'> Cancel</button>
                                        </form>
                                    {% endif %}

                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
    </div>
    </div>
    <!-- Recent Sales End -->
{%  endblock content %}

templates/pages/cancel_payments_individual.html
{% extends 'snippets/base.html' %}
{% load static %}
{% load humanize %}

{%  block content %}
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Detailed Info</h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                        <th>Client:</th>
                        <td>{{ payment.client }}</td>
                        </tr>
                        <tr>
                        <th>Merchant:</th>
                        <td>{{ payment.merchant }}</td>
                        </tr>
                        <tr>
                        <th>Period:</th>
                        <td>{{ payment.period }}</td>
                        </tr>
                        <tr>
                        <th>Percantage:</th>
                        <td>{{ payment.percentage }}</td>
                        </tr>
                        <tr>
                        <th>Sender Card:</th>
                        <td>{{ payment.sender_card }}</td>
                        </tr>
                        <tr>
                        <th>Amount:</th>
                        <td>{{ payment.amount|intcomma }}</td>
                        </tr>
                        <tr>
                        <th>DATE:</th>
                        <td>{{ payment.date }}</td>
                        </tr>
                        <tr>
                        <th>Is Transaction:</th>
                        <td>{{ payment.is_transaction }}</td>
                        </tr>
                        <tr>
                        <th>Status:</th>
                        <td>{{ payment.status }}</td>
                        </tr>
                        <tr>
                        <th>Transaction ID:</th>
                        <td>{{ payment.tr_id }}</td>
                        </tr>
                        <tr>
                        <th>Created Date:</th>
                        <td>{{ payment.created_at }}</td>
                        </tr>
                        <tr>
                        <th>Update Date:</th>
                        <td>{{ payment.updated_at }}</td>
                        </tr>

                        </thead>
                    </table>
                        <form action='{% url 'main:cancel-payment-proceed' payment.id %}' method='GET'>
                            <button class="btn btn-danger m-1" type='submit' onclick="return confirm('Are you sure?');">Cancel Payment</button>
                        </form>
                </div>
            </div>
        </div>
    </div>

{%  endblock content %}

templates/pages/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/pages/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DASHMIN - Bootstrap Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sign In Start -->
        <form class="container-fluid" method="post">{% csrf_token %}
        <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-light rounded p-4 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a href="{% url 'main:home' %}" class="">
                                <h4 class="text-primary"><i class="fa me-3"></i>Merchant Unired</h4>
                            </a>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="floatingInput" placeholder="Merchant Savdo" name="username">
                            <label for="floatingInput" >Username</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div>
{#                            <a href="">Forgot Password</a>#}
                        </div>
                        <input type="hidden" name="next" value="{% url 'main:home' %}" />
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Sign In</button>
{#                        <p class="text-center mb-0">Don't have an Account? <a href="">Sign Up</a></p>#}
                    </div>
                </div>
            </div>
        </div>
        </form>
        <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>